CREATE DATABASE [DATABASE_N5CGL_TINY_PARA] ON PRIMARY 
(NAME = N'DATABASE_N5CGL_TINY_PARA', FILENAME = N'f:\db\DATABASE_N5CGL_TINY_PARA.MDF', SIZE = 100GB, MAXSIZE = UNLIMITED, FILEGROWTH = 0 ) 

LOG ON 
(NAME = N'DATABASE_N5CGL_TINY_PARA_log', FILENAME = N'f:\db\DATABASE_N5CGL_TINY_PARA_log.LDF', SIZE = 100MB, MAXSIZE = UNLIMITED, FILEGROWTH = 10MB ) 
 COLLATE Japanese_CI_AS
GO 
ALTER DATABASE [DATABASE_N5CGL_TINY_PARA] SET RECOVERY SIMPLE
GO 
GO
