CREATE DATABASE [DATABASE_N5CGL_TINY] ON PRIMARY 
(NAME = N'DATABASE_N5CGL_TINY', FILENAME = N'f:\db\DATABASE_N5CGL_TINY.MDF', SIZE = 12000GB, MAXSIZE = UNLIMITED, FILEGROWTH = 0 ) 

LOG ON 
(NAME = N'DATABASE_N5CGL_TINY_log', FILENAME = N'f:\db\DATABASE_N5CGL_TINY_log.LDF', SIZE = 100MB, MAXSIZE = UNLIMITED, FILEGROWTH = 10MB ) 
 COLLATE Japanese_CI_AS
GO 
ALTER DATABASE [DATABASE_N5CGL_TINY] SET RECOVERY SIMPLE
GO 
alter server configuration
set buffer pool extension on
(FILENAME = N'g:\db\DATABASE_N5CGL_TINY.BPE', SIZE = 120GB )
GO 
GO
