//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TcpSp2.rc
//
#define IDD_TCPSP                       102
#define IDI_ICON1                       108
#define IDI_INFO                        109
#define IDI_OKNG                        110
#define IDI_ICON2                       115
#define IDI_ICON3                       116
#define IDC_START                       1000
#define IDC_BUTTON_SEND                 1000
#define IDC_BUTTON_SEND1                1000
#define IDC_BUTTON_MAKESOCK             1001
#define IDC_BUTTON_CONNECT              1001
#define IDC_BUTTON_CONNECT1             1001
#define IDC_EDIT_MSG                    1002
#define IDC_EDIT_MSG1                   1002
#define IDC_LIST_STATUS                 1003
#define IDC_BUTTON_CLOSE                1004
#define IDC_BUTTON_CLOSE1               1004
#define IDC_EDIT_PORT                   1005
#define IDC_EDIT_PORT1                  1005
#define IDC_EDIT_IP                     1006
#define IDC_BUTTON_CONNECT2             1006
#define IDC_BUTTON_SEND2                1007
#define IDC_EDIT_IP3                    1007
#define IDC_BUTTON_CLOSE2               1008
#define IDC_EDIT_PORT3                  1008
#define IDC_EDIT_MSG2                   1009
#define IDC_EDIT_PORT2                  1010
#define IDC_MODE_AUTO                   1011
#define IDC_EDIT_IP1                    1011
#define IDC_BUTTON_CONNECT3             1011
#define IDC_MODE_MANU                   1012
#define IDC_EDIT_IP2                    1012
#define IDC_RADIO_CONNECT               1012
#define IDC_RADIO_ACCEPT                1013
#define IDC_COMBO1                      1014
#define IDC_RADIO_CONNECT3              1014
#define IDC_RADIO_ACCEPT3               1015
#define IDC_FILESD                      1016
#define IDC_BUTTON_CLOSE3               1016
#define IDC_RADIO1_TEXT_FORM            1017
#define IDC_RADIO1_DEF_FORM             1018
#define IDC_BUTTON1_FILERD              1019
#define IDC_LIST_DATA                   1020
#define IDC_BUTTON_SEND3                1021
#define IDC_RADIO2_TEXT                 1022
#define IDC_RADIO2_FILE                 1023
#define IDC_STATIC1                     1024
#define IDC_RADIO3_SEQ                  1025
#define IDC_CNT_FILE                    1025
#define IDC_RADIO3_NML                  1026
#define IDC_BUTTON_SET                  1027
#define IDC_RADIO3_YOBI1                1028
#define IDC_BUTTON1_FILERD2             1029
#define IDC_BUTTON1_FILERD3             1030
#define IDC_BUTTON1_UP                  1031
#define IDC_CHECK1_SEND                 1032
#define IDC_BUTTON1_DOWN                1032
#define IDC_RADIO2_ASC                  1033
#define IDC_CHECK1_RECV                 1034
#define IDC_RADIO2_EBC                  1035
#define IDC_CHECK2_TRACE                1036
#define IDC_EDIT1_TRACE                 1037
#define IDC_RADIO2_ASC2                 1038
#define IDC_RECV_USR_NAME               1038
#define IDC_RECV_AUTO_NAME              1039
#define IDC_RECV_FILE                   1043
#define IDC_RECV_USR_FILE               1044
#define IDC_RECV_AUTO_FILE              1045
#define IDC_SCH_CHECK                   1047
#define IDC_CYC_CHECK                   1048
#define IDC_VERSION                     1049
#define IDC_SCH_READ_BTN                1050
#define IDC_EDIT_BTN                    1051
#define IDC_EDITCLS_BTN                 1052
#define IDC_SCH_EDIT_BTN                1053
#define IDC_SCH_REREAD_BTN              1054
#define IDC_SINA_READ_BTN               1055
#define IDC_SCH_NAME                    1056
#define IDC_EDIT_NAME                   1057
#define IDC_SINA_NAME                   1058
#define IDC_STATIC_DIR                  1059
#define IDC_TYPE_READ_BTN               1059
#define IDC_TRACE_BTN                   1060
#define IDC_CTRL_LOAD                   1061
#define IDC_CTRL_SAVE                   1062
#define IDC_LIST_LOAD                   1063
#define IDC_SINA_CHECK                  1063
#define IDC_LIST_SAVE                   1064
#define IDC_SINA_EDIT_BTN               1064
#define IDC_SINA_REREAD_BTN             1065
#define IDC_RECV_BTN                    1066
#define IDC_TCP                         1067
#define IDC_AUTO_RECV_BTN               1067
#define IDC_UDP                         1068
#define IDC_RETRY_CHECK                 1068
#define IDC_RECV_SINA_BTN               1069
#define IDC_SINA_BTN                    1070
#define IDC_COMBO2                      1070
#define IDC_COUNT_BTN                   1070
#define IDC_COUNTCLS_BTN                1071
#define IDC_COUNT_NAME                  1072
#define IDC_RSINA_STOP                  1075
#define IDC_SINA_STOP                   1076
#define IDC_CLS_BTN                     1077
#define IDC_TRACE_CLS_BTN               1077
#define IDC_SINA_CLS_BTN                1078
#define IDCANCEL_BTN                    1079
#define IDC_RECV_CLS_BTN                1079
#define IDC_SCH_CLS_BTN                 1081
#define IDC_MSGBOX_TEXT                 1081
#define IDC_OKNG_TEXT                   1082
#define IDC_OK                          1084
#define IDC_NG                          1085

#define IDC_ENETB                       1110
#define IDC_RADIO3_ASC                  1120
#define IDC_RADIO3_EBC                  1121
#define IDC_SETEB                       1122
#define IDCANCEL3                       1123
#define IDC_RADIO3_NTRN                 1124
#define IDC_RADIO3__TRN                 1125
#define IDC_EDIT_EB00                   1130
#define IDC_EDIT_EB01                   1131
#define IDC_EDIT_EB02                   1132
#define IDC_EDIT_EB03                   1133
#define IDC_EDIT_EB04                   1134
#define IDC_EDIT_EB05                   1135
#define IDC_EDIT_EB06                   1136

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        118
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
