//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// ZZ_EPC.rc で使用
//
#define IDD_ZZ_EPC_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDC_LIST1                       1000
#define IDC_BUTTON1                     1001
#define IDC_UDPRECV                     1001
#define IDC_PUTKIZU                     1002
#define IDC_KIZUCNT                     1003
#define IDC_KIZUCNT1                    1003
#define IDC_BUTTON2                     1004
#define IDC_CNGKIZU                     1004
#define IDC_KIZUCNT2                    1004
#define IDC_FRMCNT                      1005
#define IDC_FRMCNT1                     1005
#define IDC_CNGFRM                      1006
#define IDC_FRMCNT2                     1006
#define IDC_KIZUTYPE                    1007
#define IDC_KIZUTYPE1                   1007
#define IDC_KIZUGRADE                   1008
#define IDC_KIZUGRADE1                  1008
#define IDC_CHGTYPE                     1009
#define IDC_KIZUTYPE2                   1009
#define IDC_BUTTON5                     1010
#define IDC_CHGGRADE                    1010
#define IDC_KIZUGRADE2                  1010
#define IDC_BR_CENTER_ANGLE1            1011
#define IDC_GAIN_R                      1012
#define IDC_BR_OV_R_ANGLE1              1013
#define IDC_BR_OV_L_ANGLE1              1014
#define IDC_BR_CENTER_ANGLE2            1015
#define IDC_BR_OV_R_ANGLE2              1016
#define IDC_BR_OV_L_ANGLE2              1017
#define IDC_BR_CENTER_ANGLE3            1018
#define IDC_BR_OV_R_ANGLE3              1019
#define IDC_BR_OV_L_ANGLE3              1020
#define IDC_BR_CENTER_ANGLE4            1021
#define IDC_BR_OV_R_ANGLE4              1022
#define IDC_BR_OV_L_ANGLE4              1023
#define IDC_CHANGE_BRIGHTNESS           1024
#define IDC_GAIN_G                      1025
#define IDC_GAIN_B                      1026
#define IDC_CHANGE_CAMGAIN              1027
#define IDC_EDGE                        1028
#define IDC_CHANGE_CAMGAIN2             1029
#define IDC_CHANGE_EDGE                 1029
#define IDC_PUTEDGE                     1030
#define IDC_KIZUCNT3                    1031
#define IDC_FRMCNT3                     1032
#define IDC_KIZUTYPE3                   1033
#define IDC_KIZUGRADE3                  1034
#define IDC_COMBO                       1035
#define IDC_CYCLE1                      1035
#define IDC_CNG_KIZU1                   1036
#define IDC_STOP_KIZU1                  1037
#define IDC_CNG_KIZU2                   1038
#define IDC_STOP_KIZU2                  1039
#define IDC_CNG_KIZU3                   1040
#define IDC_STOP_KIZU3                  1041
#define IDC_KIZUCNT4                    1042
#define IDC_FRMCNT4                     1043
#define IDC_KIZUTYPE4                   1044
#define IDC_KIZUGRADE4                  1045
#define IDC_CNG_KIZU4                   1046
#define IDC_STOP_KIZU4                  1047
#define IDC_KIZUCNT5                    1048
#define IDC_FRMCNT5                     1049
#define IDC_KIZUTYPE5                   1050
#define IDC_KIZUGRADE5                  1051
#define IDC_CNG_KIZU5                   1052
#define IDC_STOP_KIZU5                  1053
#define IDC_UPDATE                      1054
#define IDC_UPDATE2                     1055
#define IDC_CYCLE2                      1055
#define IDC_CYCLE3                      1056
#define IDC_CYCLE4                      1057
#define IDC_FRMCNT10                    1058
#define IDC_CYCLE5                      1058
#define IDC_CHECK1                      1059
#define IDC_SKIP                        1059
#define IDC_CHECK2                      1060
#define IDC_EDGE2                       1061
#define IDC_SHRINKRATIO                 1061
#define IDC_CAM_ID                      1062
#define IDC_EDGE3                       1063
#define IDC_CAM_GAIN_1                  1064
#define IDC_CAM_GAIN_2                  1065
#define IDC_CAM_GAIN_3                  1066
#define IDC_CAM_EXP_1                   1067
#define IDC_CAM_EXP_2                   1068
#define IDC_CAM_EXP_3                   1069
#define IDC_CAM_VOLT_1                  1070
#define IDC_CAM_TEMP_1                  1071
#define IDC_POS_X                       1072
#define IDC_CHANGE_CAM_GAIN             1073
#define IDC_CHECK3                      1074
#define IDC_USE_SMEM                    1074
#define IDC_COMBO1                      1075
#define IDC_CHANGE_CAM_EXP              1076
#define IDC_CHANGE_CAM_VOLT             1077
#define IDC_CHANGE_BRIGHTNESS5          1078
#define IDC_CHANGE_CAM_TEMP             1078
#define IDC_CHANGE_CAM_SHRINKRATIO      1079

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
